Controllers/GatewayController.cs
using System.Net.Http.Headers;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Web.Data;
using Web.Models;

namespace Web.Controllers;

public class GatewayController: Controller
{
  private readonly ApplicationDbContext _context;
  private readonly HttpClient _client;
  [TempData] public string FlashMessage { get; set; }
  [TempData] public string FlashClass { get; set; }

  public GatewayController(ApplicationDbContext context)
  {
    _context = context;
    _client = new HttpClient();
  }

  [Route("/gateways")]
  public IActionResult Index()
  {
    return View();
  }

  [Route("/gateways/webpay")]
  public async Task<IActionResult> GatewayWebpay()
  {
    var data = new {
      buy_order = "buyOrder12345678",
      session_id = new DateTimeOffset(DateTime.Now).ToUnixTimeSeconds(),
      amount = 1000,
      return_url = "http://127.0.0.1:5281/gateways/webpay/response"
    };
    string contentType = "application/json";
    _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(contentType));
    _client.DefaultRequestHeaders.Add("Tbk-Api-Key-Id", _context.VariablesGlobales.Find(2).Valor);
    _client.DefaultRequestHeaders.Add("Tbk-Api-Key-Secret", _context.VariablesGlobales.Find(3).Valor);

    var result = await _client.PostAsJsonAsync(_context.VariablesGlobales.Find(1).Valor, data);
    string responseBody = await result.Content.ReadAsStringAsync();
    WebpayToken webpayToken = JsonConvert.DeserializeObject<WebpayToken>(responseBody);


    Console.WriteLine($"token = {webpayToken.Token} | URL = {webpayToken.Url}");

    return View(webpayToken);
  }

  [Route("/gateways/webpay/response")]
  public async Task<IActionResult> GatewayWebpayResponse([FromQuery(Name = "token_ws")] string token_ws)
  {
    _client.DefaultRequestHeaders.Add("Tbk-Api-Key-Id", _context.VariablesGlobales.Find(2).Valor);
    _client.DefaultRequestHeaders.Add("Tbk-Api-Key-Secret", _context.VariablesGlobales.Find(3).Valor);
    var result = await _client.PutAsJsonAsync($"{_context.VariablesGlobales.Find(1).Valor}/{token_ws}", new {});
    string responseBody = await result.Content.ReadAsStringAsync();
    WebpayRespuesta webpayRespuesta = JsonConvert.DeserializeObject<WebpayRespuesta>(responseBody);

    return View(webpayRespuesta);
  }

  // ########## PAYPAL ########## //
  private async Task<PaypalToken> ReturnToken()
  {
    var data = new Dictionary<string, string>
    {
      {"grant_type", "client_credentials"}
    };
    HttpClient client = new();
    var authToken = Encoding.ASCII.GetBytes($"{_context.VariablesGlobales.Find(5).Valor}:{_context.VariablesGlobales.Find(6).Valor}");
    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(authToken));
    var result = await client.PostAsync($"{_context.VariablesGlobales.Find(4).Valor}/v1/oauth2/token", new FormUrlEncodedContent(data));
    string responseBody = await result.Content.ReadAsStringAsync();

    return JsonConvert.DeserializeObject<PaypalToken>(responseBody);
  }

  [Route("/gateways/paypal")]
  public async Task<IActionResult> GatewayPaypal()
  {
    PaypalToken paypalToken = await ReturnToken();
    string order = $"order_{new DateTimeOffset(DateTime.UtcNow).ToUnixTimeSeconds()}";
    int amount = 10;
    // Pay Order
    var data = new
    {
      intent = "CAPTURE",
      purchase_units = new[] {
        new {
          reference_id = order,
          amount = new {
            currency_code = "USD",
            value = $"{amount}.0"
          },
        },
      },
      payment_source = new {
        paypal = new {
          experience_context = new {
            payment_method_preference = "IMMEDIATE_PAYMENT_REQUIRED",
            payment_method_selected = "PAYPAL",
            brand_name = "Klee",
            locale = "en-EN",
            landing_page = "LOGIN",
            shipping_preference = "NO_SHIPPING",
            user_action = "PAY_NOW",
            return_url = "http://127.0.0.1:5281/gateways/paypal/response",
            cancel_url = "http://127.0.0.1:5281/gateways/paypal/cancel"
          }
        }
      }
    };

    _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
    _client.DefaultRequestHeaders.Add("Authorization", $"Bearer {paypalToken.AccessToken}");
    _client.DefaultRequestHeaders.Add("PayPal-Request-Id", order);

    var result = await _client.PostAsJsonAsync($"{_context.VariablesGlobales.Find(4).Valor}/v2/checkout/orders", data);
    string responseBody = await result.Content.ReadAsStringAsync();

    PaypalOrder paypalOrder = JsonConvert.DeserializeObject<PaypalOrder>(responseBody);
    PaypalViewModel paypal = new() {
      PaypalToken = paypalToken,
      PaypalOrder = paypalOrder
    };

    // return Content($"Token={paypalToken.AccessToken}");
    return View(paypal);
  }

  [Route("/gateways/paypal/response")]
  public async Task<IActionResult> GateWayPaypalResponse([FromQuery(Name="token")] string token)
  {
    PaypalToken paypalToken = await ReturnToken();
    _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
    _client.DefaultRequestHeaders.Add("Authorization", $"Bearer {paypalToken.AccessToken}");
    var result = await _client.PostAsJsonAsync($"{_context.VariablesGlobales.Find(4).Valor}/v2/checkout/orders/{token}/capture", new {});
    string responseBody = await result.Content.ReadAsStringAsync();
    PaypalOrder paypalOrder = JsonConvert.DeserializeObject<PaypalOrder>(responseBody);

    return View(paypalOrder);
  }

  [Route("/gateways/paypal/cancel")]
  public IActionResult GateWayPaypalCancel([FromQuery(Name="token")] string token)
  {
    ViewBag.Token = token;

    return View();
  }


  // ########## STRIPE ########## //
  // https://dashboard.stripe.com/test/apikeys
  // https://stripe.com/docs/testing?locale=es-419
  // VISA Card 4242424242424242 -> https://docs.stripe.com/testing
  // https://stripe.com/docs/api/products/create
  // https://stripe.com/docs/api/prices/create
  // https://stripe.com/docs/api/checkout/sessions/create
  private async Task<StripeId> ReturnStripeId(string endpoint, Dictionary<string, string> data)
  {
    HttpClient client = new();
    client.DefaultRequestHeaders.Add("Authorization", $"Bearer {_context.VariablesGlobales.Find(9).Valor}");
    var result = await client.PostAsync($"{_context.VariablesGlobales.Find(7).Valor}{endpoint}", new FormUrlEncodedContent(data));
    string responseBody = await result.Content.ReadAsStringAsync();
    return JsonConvert.DeserializeObject<StripeId>(responseBody);
  }

  [Route("/gateways/stripe")]
  public async Task<IActionResult> GatewayStripe()
  {
    int amount = 100;
    string order = "order_123456";
    StripeId product = await ReturnStripeId
    (
      "/v1/products",
      new Dictionary<string, string> {
        { "name" , "generic" }
      }
    );

    StripeId price = await ReturnStripeId
    (
      "/v1/prices",
      new Dictionary<string, string> {
        {"unit_amount", $"{amount}"},
        {"currency", "usd"},
        {"product", product.Id}
      }
    );

    StripeId checkout = await ReturnStripeId
    (
      "/v1/checkout/sessions",
      new Dictionary<string, string>
      {
        {"success_url", $"http://127.0.0.1:5281/gateways/stripe/response?stripe={order}"},
        {"currency", "usd"},
        {"line_items[0][price]", $"{price.Id}"},
        {"line_items[0][quantity]", "1"},
        {"mode", "payment"}
      }
    );

    ViewBag.Price = amount;
    ViewBag.Order = order;

    // return Content($"Product = {product.Id} | Price = {price.Id} | Order = {checkout.Id} | URL = {checkout.Url}");
    return View(checkout);
  }

  [Route("/gateways/stripe/response")]
  public IActionResult GatewayStripeResponse([FromQuery(Name = "stripe")] string stripe)
  {
    ViewBag.Token = stripe;
    return View();
  }
}

Views/Gateway/GateWayPaypalCancel.cshtml
@{
  ViewData["Title"] = "Payment Gateways";
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="breadcrumb-item"><a asp-controller="Gateway" asp-action="Index">Payment Gateways</a></li>
    <li class="breadcrumb-item"><a asp-controller="Gateway" asp-action="GatewayPaypal">Paypal</a></li>
    <li class="breadcrumb-item active" aria-current="page">Response</li>
  </ol>
</nav>

<h2 class="text-center">Gateway Paypal Implementation</h2>

<div class="alert alert-danger alert-dismissible fade show" role="alert">
  Your order: <strong>@ViewBag.Token</strong> was cancelled.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

Views/Gateway/GateWayPaypalResponse.cshtml
@model Web.Models.PaypalOrder;
@{
  ViewData["Title"] = "Payment Gateways";
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="breadcrumb-item"><a asp-controller="Gateway" asp-action="Index">Payment Gateways</a></li>
    <li class="breadcrumb-item"><a asp-controller="Gateway" asp-action="GatewayPaypal">Paypal</a></li>
    <li class="breadcrumb-item active" aria-current="page">Response</li>
  </ol>
</nav>

<h2 class="text-center">Gateway Paypal Implementation</h2>

<div class="alert alert-success alert-dismissible fade show" role="alert">
  Your payment was registered successfully, assosiated to order: <strong>@Model.Id</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

Views/Gateway/GateWayStripeResponse.cshtml
@model Web.Models.StripeId;
@{
  ViewData["Title"] = "Payment Gateways";
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="breadcrumb-item"><a asp-controller="Gateway" asp-action="Index">Payment Gateways</a></li>
    <li class="breadcrumb-item"><a asp-controller="Gateway" asp-action="GatewayStripe">Stripe</a></li>
    <li class="breadcrumb-item active" aria-current="page">Response</li>
  </ol>
</nav>

<h2 class="text-center">Gateway Paypal Implementation</h2>

<div class="alert alert-success alert-dismissible fade show" role="alert">
  Pay order: <strong>@ViewBag.Token</strong> was successfully created!
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

Views/Gateway/GatewayPaypal.cshtml
@model Web.Models.PaypalViewModel;
@{
  ViewData["Title"] = "Payment Gateways";
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="breadcrumb-item"><a asp-controller="Gateway" asp-action="Index">Payment Gateways</a></li>
    <li class="breadcrumb-item active" aria-current="page">Paypal</li>
  </ol>
</nav>

<h2 class="text-center">Gateway Paypal Implementation</h2>
<ul>
  <li><strong>Product:</strong> Coffe Table</li>
  <li><strong>Value:</strong> $100.00</li>
  <li><strong>Quantity:</strong> 2</li>
  <li><strong>Buy Order:</strong> @Model.PaypalOrder.Id</li>
  <li><strong>Token: </strong> @Model.PaypalToken.AccessToken</li>
  <li><strong>URL: </strong> https://www.sandbox.paypal.com/checkoutnow?token=@Model.PaypalOrder.Id</li>
</ul>
<form action="#" method="post" name="form">
  <input type="hidden" name="token_ws" id="token_ws" value="@Model.PaypalToken.AccessToken" />
  <a href=" https://www.sandbox.paypal.com/checkoutnow?token=@Model.PaypalOrder.Id" class="btn btn-warning">
    <i class="fas fa-dollar-sign"></i> Pay
  </a>
</form>

Views/Gateway/GatewayStripe.cshtml
@model Web.Models.StripeId;
@{
  ViewData["Title"] = "Payment Gateways";
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="breadcrumb-item"><a asp-controller="Gateway" asp-action="Index">Payment Gateways</a></li>
    <li class="breadcrumb-item active" aria-current="page">Stripe</li>
  </ol>
</nav>

<h2 class="text-center">Gateway Paypal Implementation</h2>
<ul>
  <li><strong>Product:</strong> Coffe Table</li>
  <li><strong>Value:</strong> @ViewBag.Price </li>
  <li><strong>Quantity:</strong> 2</li>
  <li><strong>Buy Order:</strong> @ViewBag.Order</li>
  <li><strong>Token: </strong> @Model.Id </li>
  <li><strong>URL: </strong> @Model.Url </li>
</ul>

<a href="@Model.Url" class="btn btn-info">
  <i class="fab fa-stripe"></i> Pay
</a>

Views/Gateway/GatewayWebpay.cshtml
@model Web.Models.WebpayToken;
@{
  ViewData["Title"] = "Payment Gateways";
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="breadcrumb-item"><a asp-controller="Gateway" asp-action="Index">Payment Gateways</a></li>
    <li class="breadcrumb-item active" aria-current="page">Webpay Transbank</li>
  </ol>
</nav>

<h2 class="text-center">Webpay Gateway</h2>
<ul>
  <li><strong>Product:</strong> Coffe Table</li>
  <li><strong>Value:</strong> $100.00</li>
  <li><strong>Quantity:</strong> 2</li>
  <li><strong>Buy Order:</strong> 34512</li>
  <li><strong>URL: </strong> @Model.Url</li>
  <li><strong>Token: </strong> @Model.Token</li>
</ul>
<form action="@Model.Url" method="post" name="form">
  <input type="hidden" name="token_ws" id="token_ws" value="@Model.Token" />
  <a href="javascript:void(0);" onclick="document.form.submit()" class="btn btn-danger">
    <i class="fas fa-dollar-sign"></i> Pay
  </a>

</form>

Views/Gateway/GatewayWebpayResponse.cshtml
@model Web.Models.WebpayRespuesta;
@{
  ViewData["Title"] = "Payment Gateways";
}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="breadcrumb-item"><a asp-controller="Gateway" asp-action="Index">Payment Gateways</a></li>
    <li class="breadcrumb-item"><a asp-controller="Gateway" asp-action="GatewayWebpay">Gateway Webpay</a></li>
    <li class="breadcrumb-item active" aria-current="page">Webpay Response</li>
  </ol>
</nav>

<h1>Webpay Response</h1>
<ul>
  <li>VCI: <span>@Model.Vci</span> </li>
  <li>amount: <span>@Model.Amount</span> </li>
  <li>status: <span>@Model.Status</span> </li>
  <li>buy_order: <span>@Model.Buy_Order</span> </li>
  <li>session_id: <span>@Model.Session_Id</span> </li>
  <li>card_detail: <span>@Model.Card_Detail.Card_Number</span> </li>
  <li>accounting_date: <span>@Model.Accounting_Date</span> </li>
  <li>transaction_date: <span>@Model.Transaction_Date</span> </li>
  <li>authorization_code: <span>@Model.Authorization_Code</span> </li>
  <li>payment_type_code: <span>@Model.Payment_Type_Code</span> </li>
  <li>response_code: <span>@Model.Response_Code</span> </li>
  <li>installments_number: <span>@Model.Installments_Number</span> </li>
</ul>

Views/Gateway/Index.cshtml
@{
  ViewData["Title"] = "Payment Gateway";
}
<h2 class="text-center">Payment Gateway</h2>
<ul>
  <hr />
  <li>
    <a asp-controller="Gateway" asp-action="GatewayWebpay" class="p-2 link-secondary">
      <i class="fas fa-dollar-sign"></i> Transbank Webpay
    </a>
  </li>
  <hr />
  <li>
    <a asp-controller="Gateway" asp-action="GatewayPaypal" class="p-2 link-secondary">
      <i class="fab fa-paypal"></i> Paypal
    </a>
  </li>
  <hr />
  <li>
    <a asp-controller="Gateway" asp-action="GatewayStripe" class="p-2 link-secondary">
      <i class="fab fa-stripe"></i> Stripe
    </a>
  </li>
</ul>